# ArgoCD App: Gateway API CRDs
# @author Shanaka Jayasundera - shanakaj@gmail.com
#
# LAYER 3: K8s Customizations
# Sync Wave: 0 (first - CRDs must be installed before anything else)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api.git
    targetRevision: v1.2.0
    path: config/crd/standard

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: false  # Don't prune CRDs
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
