# ArgoCD App: Kong Gateway with Konnect Integration
# @author Shanaka Jayasundera - shanakaj@gmail.com
#
# LAYER 3: K8s Customizations
# Sync Wave: 1 (after Gateway API CRDs)
#
# NOTE: Before deploying, run scripts/setup-konnect.sh to create the
# required Kubernetes secrets for Konnect connection.
# Update the <your-cp> placeholders with your Control Plane ID from Konnect.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://charts.konghq.com
    chart: kong
    targetRevision: 2.38.0
    helm:
      valueFiles: []
      values: |
        # Use Kong Gateway Enterprise image (required for Konnect)
        image:
          repository: kong/kong-gateway
          tag: "3.9"

        # Enable Gateway API support
        gateway:
          enabled: true

        # Kong Ingress Controller
        ingressController:
          enabled: true
          installCRDs: true
          env:
            feature_gates: "GatewayAlpha=true"

        # Konnect data plane connection (AU region)
        # Kong reports telemetry/analytics to Konnect; KIC manages routing config
        env:
          cluster_control_plane: "b5ec5fb109.au.cp0.konghq.com:443"
          cluster_server_name: "b5ec5fb109.au.cp0.konghq.com"
          cluster_telemetry_endpoint: "b5ec5fb109.au.tp0.konghq.com:443"
          cluster_telemetry_server_name: "b5ec5fb109.au.tp0.konghq.com"
          cluster_cert: /etc/secrets/konnect-client-tls/tls.crt
          cluster_cert_key: /etc/secrets/konnect-client-tls/tls.key
          lua_ssl_trusted_certificate: system

        # Mount Konnect certificate secrets
        secretVolumes:
          - konnect-client-tls

        # Kong Gateway (Data Plane)
        # NLB is Terraform-managed for CloudFront VPC Origin integration
        # Kong pods registered via TargetGroupBinding CRD (AWS LB Controller)
        proxy:
          enabled: true
          type: ClusterIP  # NLB is Terraform-managed, not auto-created
          http:
            enabled: true
            containerPort: 8000
            servicePort: 80
          tls:
            enabled: true
            containerPort: 8443
            servicePort: 443

        # Admin API (disabled for security)
        admin:
          enabled: false

        # Status endpoint
        status:
          enabled: true
          http:
            enabled: true
            containerPort: 8100

        # Resources
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

        # Tolerations for system nodes
        tolerations:
          - key: "CriticalAddonsOnly"
            operator: "Exists"
            effect: "NoSchedule"

        # Pod disruption budget for HA
        podDisruptionBudget:
          enabled: true
          minAvailable: 1

        # Replicas
        replicaCount: 2

  destination:
    server: https://kubernetes.default.svc
    namespace: kong

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
