# ArgoCD App: Kong Gateway Data Plane (Split Deployment)
# @author Shanaka Jayasundera - shanakaj@gmail.com
#
# LAYER 3: K8s Customizations
# Sync Wave: 1 (after Gateway API CRDs)
#
# SPLIT DEPLOYMENT: Data plane only — no KIC sidecar.
# KIC is deployed separately via 02b-kong-controller.yaml
# KIC pushes config via admin API and syncs to Konnect for visibility/licensing.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://charts.konghq.com
    chart: kong
    targetRevision: 2.38.0
    helm:
      valueFiles: []
      values: |
        # Kong Gateway Enterprise image (required for Konnect)
        image:
          repository: kong/kong-gateway
          tag: "3.9"

        # No KIC in data plane (deployed separately via 02b-kong-controller.yaml)
        # KIC manages routing via admin API + syncs to Konnect
        ingressController:
          enabled: false

        # DB-less mode — KIC pushes config via admin API
        # KIC handles ALL Konnect communication: config sync, node registration,
        # and license fetch via <region>.kic.api.konghq.com.
        #
        # KONNECT ANALYTICS LIMITATION (KIC + Gateway Discovery pattern):
        # Native Konnect analytics requires role=data_plane to activate the
        # telemetry subsystem. However, role=data_plane forcefully disables
        # the admin API — even with explicit admin_listen override — which
        # breaks KIC gateway discovery. This is a fundamental Kong limitation.
        # API observability is provided via the Prometheus plugin instead
        # (see k8s/kong/prometheus-plugin.yaml).
        env:
          database: "off"

        # Admin API enabled for KIC gateway discovery (ClusterIP only)
        admin:
          enabled: true
          type: ClusterIP
          http:
            enabled: true
            containerPort: 8001

        # Kong Gateway (Data Plane)
        # NLB is Terraform-managed for CloudFront VPC Origin integration
        # Kong pods registered via TargetGroupBinding CRD (AWS LB Controller)
        proxy:
          enabled: true
          type: ClusterIP  # NLB is Terraform-managed, not auto-created
          http:
            enabled: true
            containerPort: 8000
            servicePort: 80
          tls:
            enabled: true
            containerPort: 8443
            servicePort: 443

        # Readiness probe: use /status (Kong is running) instead of /status/ready
        # (Kong has config). Without this, DB-less Kong without initial config returns
        # 503 on /status/ready, preventing KIC from discovering pods via admin API.
        readinessProbe:
          httpGet:
            path: /status
            port: status
            scheme: HTTP

        # Status endpoint
        status:
          enabled: true
          http:
            enabled: true
            containerPort: 8100

        # Resources
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

        # Tolerations for system nodes
        tolerations:
          - key: "CriticalAddonsOnly"
            operator: "Exists"
            effect: "NoSchedule"

        # Pod disruption budget for HA
        podDisruptionBudget:
          enabled: true
          minAvailable: 1

        # Replicas
        replicaCount: 2

  destination:
    server: https://kubernetes.default.svc
    namespace: kong

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
