# ArgoCD App: Kong Gateway with Konnect Integration
# @author Shanaka Jayasundera - shanakaj@gmail.com
#
# LAYER 3: K8s Customizations
# Sync Wave: 1 (after Gateway API CRDs)
#
# NOTE: Before deploying, run scripts/setup-konnect.sh to create the
# required Kubernetes secrets for Konnect connection.
# Update the <your-cp> placeholders with your Control Plane ID from Konnect.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://charts.konghq.com
    chart: kong
    targetRevision: 2.38.0
    helm:
      valueFiles: []
      values: |
        # Use Kong Gateway Enterprise image (required for Konnect)
        image:
          repository: kong/kong-gateway
          tag: "3.9"

        # Enable Gateway API support
        gateway:
          enabled: true

        # Kong Ingress Controller with Konnect integration
        ingressController:
          enabled: true
          installCRDs: true
          env:
            feature_gates: "GatewayAlpha=true"
          # Required for Konnect integration
          gatewayDiscovery:
            enabled: true
            adminApiService:
              name: "kong-gateway-kong-admin"
              namespace: "kong"
          # KIC 3.x native Konnect integration
          konnect:
            enabled: true
            apiHostname: "us.kic.api.konghq.com"
            controlPlaneID: "d7772b3e-a7a6-4a7b-998e-5b050321def1"
            tlsClientCert:
              secretName: "konnect-client-tls"
            license:
              enabled: true

        # Kong Gateway (Data Plane)
        # NLB is Terraform-managed for CloudFront VPC Origin integration
        # Kong pods registered via TargetGroupBinding CRD (AWS LB Controller)
        proxy:
          enabled: true
          type: ClusterIP  # NLB is Terraform-managed, not auto-created
          http:
            enabled: true
            containerPort: 8000
            servicePort: 80
          tls:
            enabled: true
            containerPort: 8443
            servicePort: 443

        # Admin API (internal ClusterIP - required for KIC gateway discovery)
        admin:
          enabled: true
          type: ClusterIP
          http:
            enabled: true
            containerPort: 8001
            servicePort: 8001

        # Status endpoint
        status:
          enabled: true
          http:
            enabled: true
            containerPort: 8100

        # Resources
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

        # Tolerations for system nodes
        tolerations:
          - key: "CriticalAddonsOnly"
            operator: "Exists"
            effect: "NoSchedule"

        # Pod disruption budget for HA
        podDisruptionBudget:
          enabled: true
          minAvailable: 1

        # Replicas
        replicaCount: 2

  destination:
    server: https://kubernetes.default.svc
    namespace: kong

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
