# ArgoCD App: Kong Gateway Data Plane with Konnect Integration
# @author Shanaka Jayasundera - shanakaj@gmail.com
#
# LAYER 3: K8s Customizations
# Sync Wave: 1 (after Gateway API CRDs)
#
# SPLIT DEPLOYMENT: This is the data plane only.
# KIC is deployed separately via 02b-kong-controller.yaml
#
# NOTE: Before deploying, create the kong-cluster-cert secret:
# kubectl create secret tls kong-cluster-cert -n kong --cert=tls.crt --key=tls.key

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://charts.konghq.com
    chart: kong
    targetRevision: 2.38.0
    helm:
      valueFiles: []
      values: |
        # Kong Gateway Enterprise image (required for Konnect)
        image:
          repository: kong/kong-gateway
          tag: "3.9"

        # No KIC in data plane (deployed separately)
        ingressController:
          enabled: false

        # Konnect data plane connection (AU region)
        env:
          role: data_plane
          database: "off"
          konnect_mode: "on"
          vitals: "off"
          cluster_mtls: pki
          cluster_control_plane: "b5ec5fb109.au.cp.konghq.com"
          cluster_telemetry_endpoint: "b5ec5fb109.au.tp.konghq.com:443"
          cluster_telemetry_server_name: "b5ec5fb109.au.tp.konghq.com"
          cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
          cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
          lua_ssl_trusted_certificate: system

        # Mount Konnect certificate secret
        secretVolumes:
          - kong-cluster-cert

        # Admin API enabled for KIC gateway discovery (ClusterIP only)
        admin:
          enabled: true
          type: ClusterIP
          http:
            enabled: true
            containerPort: 8001

        # Kong Gateway (Data Plane)
        # NLB is Terraform-managed for CloudFront VPC Origin integration
        # Kong pods registered via TargetGroupBinding CRD (AWS LB Controller)
        proxy:
          enabled: true
          type: ClusterIP  # NLB is Terraform-managed, not auto-created
          http:
            enabled: true
            containerPort: 8000
            servicePort: 80
          tls:
            enabled: true
            containerPort: 8443
            servicePort: 443

        # Status endpoint
        status:
          enabled: true
          http:
            enabled: true
            containerPort: 8100

        # Resources
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

        # Tolerations for system nodes
        tolerations:
          - key: "CriticalAddonsOnly"
            operator: "Exists"
            effect: "NoSchedule"

        # Pod disruption budget for HA
        podDisruptionBudget:
          enabled: true
          minAvailable: 1

        # Replicas
        replicaCount: 2

  destination:
    server: https://kubernetes.default.svc
    namespace: kong

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
