# ArgoCD App: Users API
# @author Shanaka Jayasundera - shanakaj@gmail.com
#
# LAYER 4: Applications
# Sync Wave: 4 (after health responder)
# Deploys users-api on path /api/users with Kong plugins

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: users-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/shanaka-versent/EKS-Kong-GatewayAPI-Demo.git
    targetRevision: HEAD
    path: k8s/apps/api

  destination:
    server: https://kubernetes.default.svc
    namespace: api

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
